// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb_NLCtVglCvYVsDUNlOmKb9cD9pNfE5Q',
    appId: '1:1015101335728:web:8e021cc68e2524e54d7375',
    messagingSenderId: '1015101335728',
    projectId: 'ma-voix-c555a',
    authDomain: 'ma-voix-c555a.firebaseapp.com',
    storageBucket: 'ma-voix-c555a.appspot.com',
    measurementId: 'G-EQ6Z9BEWHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKPPbPF-mtZasJGOmYapUoWCeYmWrq_dk',
    appId: '1:1015101335728:android:506234114545be584d7375',
    messagingSenderId: '1015101335728',
    projectId: 'ma-voix-c555a',
    storageBucket: 'ma-voix-c555a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJYPdWJgTq3UL7Bb_7YHgGmbf8jwydGg',
    appId: '1:1015101335728:ios:25a4c0324c60ac1f4d7375',
    messagingSenderId: '1015101335728',
    projectId: 'ma-voix-c555a',
    storageBucket: 'ma-voix-c555a.appspot.com',
    iosClientId: '1015101335728-es6roalajo2p0pbvmq6t3f30112uv58g.apps.googleusercontent.com',
    iosBundleId: 'com.example.maVoix',
  );
}
